### ISSUE TITLE
terraform: option to apply plan from previous run

### ISSUE THREAD

**Issue by FrancisBilla** [turntabl/community.general#5]
##### SUMMARY
Currently, the module recreates temporary plan files any time you run the 'apply' or the 'plan' command. There is no way of retrieving the plan_files created by the module. so when a user wants to run an 'apply', there is no way of getting and using the plan file created from a previous 'plan' command.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
terraform module

##### ADDITIONAL INFORMATION
It would be nice to have the model take an additional parameter: for example a `plan_id` provided by the user in case they might wish to reuse a plan file. If the user does not provide the `plan_id` and a `plan_path` and he or she performs a plan before an apply, the module should also be able to retrieve the path to the last plan file generated by the user and then run the apply with the plan file retrieved.
 
```
- name: terraform 
    terraform:
      project_path: 'path_to_project/'
      plan_id: 'tmpER44'
      state: present
      check_deletes: True
```
