### ISSUE TITLE
terraform: Option to apply only when there will be no delete to resources

### ISSUE THREAD

**Issue by FrancisBilla** [turntabl/community.general#6]
**SUMMARY**

The current module does an apply irrespective of what happens to the resources but mistakes happen all the time and developers might mistakenly remove resources. Therefore it would be convenient to have an option to check for that before any changes is done to the resource.

**ISSUE TYPE**   

- Feature Pull Request

**COMPONENT NAME**

- terraform module

**ADDITIONAL INFORMATION**

The proposed module takes an optional parameter check_deletes of type boolean. It defaults to false and passed when the user intends to apply changes. The module would then run a terraform plan and check if it would destroy resources and proceed to apply the changes if there is none.

```
- name: terraform safe_mode
    terraform:
      project_path: 'path_to_project/'
      state: present
      check_deletes: True
```
